### ISSUE TITLE
Add "accordion" sections to service pages

### ISSUE THREAD

**Issue by Eylas** [Nodehex/Website#73]
Update service pages to include accordion dropdowns to hide detail but retain info on the service pages:

Detail on what accordions are here:

https://en.wikipedia.org/wiki/Accordion_(GUI)

**Comment by Spacebjorn** [comment]
isn't this the same as [issue 54](https://github.com/AeonDataServices/Website/issues/54)?

**Comment by Eylas** [comment]
It's not, what I'm talking about here is "accordions"

https://material-ui.com/components/accordion/

Jenna made a good point that we could still keep a lot of the information in if we wanted and use accordions to allow users to read more if they wish but give us the ability to hide a lot of info under bullet points.
